name: module-allocator-notebook
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.6.17
  - comm=0.2.3
  - cpython=3.14.6
  - debugpy=1.8.21
  - decorator=5.3.1
  - executing=2.2.1
  - icu=78.3
  - ipykernel=7.3.0
  - ipython=9.14.1
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jupyter_client=8.9.1
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - krb5=1.22.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=22.1.8
  - libedit=3.1.20250104
  - libexpat=2.8.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.3
  - libmpdec=4.0.0
  - libopenblas=0.3.33
  - libsodium=1.0.22
  - libsqlite=3.53.2
  - libzlib=1.3.2
  - llvm-openmp=22.1.8
  - matplotlib-inline=0.2.2
  - ncurses=6.6
  - nest-asyncio2=1.7.2
  - numpy=2.4.6
  - openssl=3.6.3
  - packaging=26.2
  - pandas=3.0.3
  - parso=0.8.7
  - pexpect=4.9.0
  - pip=26.1.2
  - platformdirs=4.10.0
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.20.0
  - python=3.14.6
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.6
  - python_abi=3.14
  - pyzmq=27.1.0
  - readline=8.3
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.7
  - traitlets=5.15.1
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wcwidth=0.8.1
  - widgetsnbextension=4.0.15
  - zeromq=4.3.5
  - zstd=1.5.7
